name:                mscheme
version:             0.1.0.0
github:              "githubuser/mscheme"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mscheme#readme>

dependencies:
- base >= 4.7 && < 5
- text == 1.2.4.1
- filepath == 1.4.2.1
- llvm-hs-pure == 9.0.0
- llvm-hs-pretty == 0.6.2.0
- containers == 0.6.2.1
- bytestring == 0.10.12.0

library:
  source-dirs:
  - src
  - app
  dependencies:
  - hashtables
  - transformers

executables:
  mscheme:
    main:                mscheme.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashtables
    - mtl
    - transformers
  mscheme2:
    main:                mscheme2.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashtables
    - mtl
    - transformers

  mschemec:
    main:                mschemec.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashtables
    - mtl
    - transformers

  mschemec2:
    main:                mschemec2.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashtables
    - mtl
    - transformers

  mschemellvm:
    main:                mschemellvm.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashtables
    - mtl
    - transformers


tests:
  mscheme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - transformers
    - hashtables
    - mscheme
    - HUnit
    - silently
    - hspec-discover
    - hspec


    
